name: CI/CD Pipeline for Flask + Vue 3

# 触发条件
on:
  push:
    branches:
      - main  # 或者你的默认分支
  pull_request:
    branches:
      - main  # 或者你的默认分支

jobs:
  # 后端测试（Flask）
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  # 假设你的后端依赖在 backend 文件夹下

      - name: Run backend tests
        run: |
          pytest backend/tests  # 假设你的后端测试在 backend/tests 目录

  # 前端测试（Vue 3）
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 或你所需的版本

      - name: Install frontend dependencies
        run: |
          cd frontend  # 假设你的前端项目在 frontend 文件夹中
          npm install  # 或 yarn install

      - name: Run frontend tests
        run: |
          cd frontend
          npm test  # 或 yarn test，执行 Vue 3 前端测试

  # 部署（部署到生产或测试环境）
  deploy:
    needs: [backend-tests, frontend-tests]  # 部署前需要通过测试
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python for Flask Deployment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # 在这里加入你的部署命令，如使用 Docker、SSH 部署到服务器或其他云平台（Heroku、AWS、GCP等）
